//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trips_and_Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public System.DateTime Date { get; set; }
        public string Destination { get; set; }
        public string Photo { get; set; }
        public string AgencyName { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
